inherit_from: .rubocop_todo.yml

require:
  rubocop-rails

Documentation:
  Enabled: false

Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
